title: Provena
description: User documentation for Provena
theme: "just-the-docs"
# remote_theme: pdmosses/just-the-docs@rec-nav-2
#logo: "/assets/images/iconRestoration.png"
search_enabled: true
toc: false
heading_anchors: true
last_edit_timestamp: true
aux_links_new_tab: true
markdown: kramdown
#aux_links:
#  "RRAP-IS M&DS":
#    - "https://mds.gbrrestoration.org/"
#  "RRAP":
#    - "https://gbrrestoration.org/"

# exclude:
#   - development.md

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"